[package]
name = "smart-memory-mcp-client"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.44", features = ["full"] }
tonic = "0.11"
prost = "0.12"
anyhow = "1.0"

[build-dependencies]
tonic-build = "0.11"
