name: CI

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false  # Don't cancel other jobs if one fails
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            platform: linux
            artifact_name: smart-memory-mcp-linux
            binary_name: smart-memory-mcp-core
          - os: windows-latest
            platform: windows
            artifact_name: smart-memory-mcp-windows
            binary_name: smart-memory-mcp-core.exe
          - os: macos-latest
            platform: macos
            artifact_name: smart-memory-mcp-macos
            binary_name: smart-memory-mcp-core

    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: 'extension/package-lock.json'

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Build Core
      working-directory: ./core
      run: cargo build --release

    - name: Test Core
      working-directory: ./core
      run: cargo test

    - name: Build Extension
      working-directory: ./extension
      run: |
        npm ci
        npm run build

    - name: Test Extension
      working-directory: ./extension
      run: npm test

    - name: Prepare Artifacts
      run: |
        mkdir -p extension/bin/${{ matrix.platform }}
        if [ "${{ matrix.os }}" = "windows-latest" ]; then
          cp core/target/release/${{ matrix.binary_name }} extension/bin/${{ matrix.platform }}/
        else
          cp core/target/release/${{ matrix.binary_name }} extension/bin/${{ matrix.platform }}/
          chmod +x extension/bin/${{ matrix.platform }}/${{ matrix.binary_name }}
        fi
      shell: bash

    - name: Upload Binary
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.artifact_name }}
        path: core/target/release/${{ matrix.binary_name }}
        if-no-files-found: error

    - name: Upload Extension Binaries
      uses: actions/upload-artifact@v3
      with:
        name: extension-bin-${{ matrix.platform }}
        path: extension/bin/${{ matrix.platform }}
        if-no-files-found: error

    - name: Package Extension (Linux only)
      if: matrix.os == 'ubuntu-latest'
      working-directory: ./extension
      run: |
        npm run package
        mkdir -p ../dist
        cp *.vsix ../dist/

    - name: Upload VSIX Package (Linux only)
      if: matrix.os == 'ubuntu-latest'
      uses: actions/upload-artifact@v3
      with:
        name: vsix-package
        path: dist/*.vsix
        if-no-files-found: error

  release:
    name: Create Release
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Download All Artifacts
      uses: actions/download-artifact@v3
      with:
        path: artifacts

    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          artifacts/smart-memory-mcp-linux/smart-memory-mcp-core
          artifacts/smart-memory-mcp-windows/smart-memory-mcp-core.exe
          artifacts/smart-memory-mcp-macos/smart-memory-mcp-core
          artifacts/vsix-package/*.vsix
        draft: false
        prerelease: false
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Publish to VS Code Marketplace
      if: success()
      run: |
        npx vsce publish -p ${{ secrets.VSCE_PAT }} --packagePath artifacts/vsix-package/*.vsix