name: Extension CI

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'extension/**'
      - '.github/workflows/extension-ci.yml'
  pull_request:
    paths:
      - 'extension/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install dependencies
        run: cd extension && npm ci
      - name: Build
        run: cd extension && npm run build
      - name: Run tests
        run: cd extension && npm test
      - name: Lint
        run: cd extension && npm run lint

  package:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install dependencies
        run: cd extension && npm ci
      - name: Package
        run: cd extension && npm run package