name: Rust CI

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'core/**'
      - '.github/workflows/rust-ci.yml'
  pull_request:
    paths:
      - 'core/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Build
        run: cd core && cargo build --verbose
      - name: Run tests
        run: cd core && cargo test --verbose
      - name: Run clippy
        run: cd core && cargo clippy -- -D warnings
      - name: Check formatting
        run: cd core && cargo fmt --check

  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Install cargo-tarpaulin
        run: cargo install cargo-tarpaulin
      - name: Generate coverage
        run: cd core && cargo tarpaulin --out Xml
      - name: Upload coverage
        uses: codecov/codecov-action@v3